version: 0.2
phases:
  install:
    commands:
      - pwd
      - ls -lthra
      - export BUCKET="dev-nelsone-deployment-artifacts-store-us-east-1"
      - aws cloudformation package --template-file template.yaml --output-template-file packaged-template.yaml --s3-bucket $BUCKET --s3-prefix lambda/lambdaAPI/deploy
    finally:
      - echo 'done build phase'
  post_build:
    commands:
      - echo Entered the post_build phase...
      - pwd
artifacts:
  type: zip
  files:
    - APPNAME_deploy.yaml